name: Bump HeadsetControl to latest release

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest release
        id: get_latest_release
        uses: actions/github-script@v4
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: 'sapd', repo: 'HeadsetControl' });

            // Find the latest non-prerelease, non-continuous release
            const stableRelease = releases.find(release => 
              !release.prerelease && 
              !release.draft && 
              release.tag_name !== 'continuous'
            );

            if (!stableRelease) {
              throw new Error('No stable release found');
            }

            // Find the Windows binary asset
            const windowsAsset = stableRelease.assets.find(asset => 
              asset.name.includes('windows') && asset.name.endsWith('.zip')
            );

            if (!windowsAsset) {
              throw new Error('No Windows binary found in release');
            }

            console.log(stableRelease.tag_name);
            console.log('Windows asset:', windowsAsset.name);
            core.setOutput('latest_tag', stableRelease.tag_name);
            core.setOutput('download_url', windowsAsset.browser_download_url);

      - name: Download file from latest release
        run: |
          wget ${{ steps.get_latest_release.outputs.download_url }} -O downloaded_file

      - name: Unzip release asset
        run: unzip -o downloaded_file -d lib/

      - name: Configure Git
        run: |
          git config --global user.name "${{vars.GIT_NAME}}"
          git config --global user.email ${{vars.GIT_EMAIL}}

      - name: Add changes to git
        run: |
          git add lib/

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump HeadsetControl to ${{ steps.get_latest_release.outputs.latest_tag }}"
          title: "Bump HeadsetControl to ${{ steps.get_latest_release.outputs.latest_tag }}"
          committer: "${{ vars.GIT_NAME }} <${{ vars.GIT_EMAIL }}>"
          author: "${{ vars.GIT_NAME }} <${{ vars.GIT_EMAIL }}>"
          branch: ${{ steps.get_latest_release.outputs.latest_tag }}
          base: master
          signoff: true
          delete-branch: true
